# Generated by Django 5.0.7 on 2024-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_restaurant_average_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
